version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: solutiondesk
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/solutiondesk
      FLASK_ENV: development
    depends_on:
      - db
volumes:
  db_data:
