[build]
  command   = "cd frontend && npm ci && npm run build"
  publish   = "frontend/build"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://ow-backend.onrender.com"
